/*******************************************************************************/
/****** Creates Call Mode Table                                           ******/
/****** Author: Tomislav Miksa                                            ******/
/****** v1.00: CREATE                                                     ******/
/*******************************************************************************/
IF EXISTS (SELECT * FROM   sysobjects WHERE  name = N'vSpeechCDR2018_Operator1') DROP view vSpeechCDR2018_Operator1
IF EXISTS (SELECT * FROM   sysobjects WHERE  name = N'vSpeechCDR2018_Operator2') DROP view vSpeechCDR2018_Operator2
IF EXISTS (SELECT * FROM   sysobjects WHERE  name = N'vSpeechCDR2018_Operator3') DROP view vSpeechCDR2018_Operator3
IF EXISTS (SELECT * FROM   sysobjects WHERE  name = N'vSpeechCDR2018_Operator4') DROP view vSpeechCDR2018_Operator4
IF EXISTS (SELECT * FROM   sysobjects WHERE  name = N'vSpeechCDR2018_Operator5') DROP view vSpeechCDR2018_Operator5
GO
CREATE VIEW [dbo].[vSpeechCDR2018_Operator1] 
AS
select   Campaign
		,File_Name_A
		,File_Name_B
		,FileID_A
		,FileId_B
		,SessionID_A
		,SessionId_B
		,Sequenz_ID_per_File_A
		,Call_Status
		,Call_Start_Time
		,Call_End_Time
		,System_A
		,System_Software_A
		,Channel_A
		,Channel_Description_A
		,System_B
		,System_Software_B
		,Channel_B
		,Channel_Description_B
		,Operator
		,Session_Type
		,Call_Direction
		,DialedNumber
		,L1_callMode_A
		,L2_callMode_A
		,L1_callMode_B
		,L2_callMode_B
		,Year
		,Week
		,Month
		,Day
		,Hour
		,G_Level_1
		,G_Level_2
		,G_Level_3
		,G_Level_4
		,G_Level_5
		,TrainType
		,Fleet
		,WagonNumber
		,WagonRepeter
		,UE_A
		,FW_A
		,IMEI_A
		,IMSI_A
		,MSISDN_A
		,UE_B
		,FW_B
		,IMEI_B
		,IMSI_B
		,MSISDN_B
		,TestId
		,direction
		,SpeedAvg
		,TestStart
		,TestEnd
		,LQ
		,L1_VoLTE_Call_Mode_LQ
		,L2_VoLTE_Call_Mode_LQ
		,qualityCode
		,LQCat
		,timeClipping
		,posFreqShift
		,negFreqShift
		,refDCOffset
		,codedDcOffset
		,delaySpread
		,codedLevel
		,delayDeviation
		,aSLrcvP56
		,activityRcvP56
		,noiseRcv
		,staticSNR
		,appl
		,ReceiveDelay
		,AmplClipping
		,MissedVoice
		,LowerFilterLimit
		,UpperFilterLimit
		,ErrCode
		,WideBand
		,BW
		,Resampling
		,Playing_Technology
		,Playing_Technology_Detailed
		,Playing_Codec
		,Playing_Codec_Detailed
		,Playing_AMR_NB_ms
		,Playing_AMR_WB_ms
		,Playing_EVS_ms
		,[Playing_AMR_NB_1.8_ms]
		,[Playing_AMR_NB_4.75_ms]
		,[Playing_AMR_NB_5.15_ms]
		,[Playing_AMR_NB_5.9_ms]
		,[Playing_AMR_NB_6.7_ms]
		,[Playing_AMR_NB_7.4_ms]
		,[Playing_AMR_NB_7.95_ms]
		,[Playing_AMR_NB_10.2_ms]
		,[Playing_AMR_NB_12.2_ms]
		,[Playing_AMR_WB_6.6_ms]
		,[Playing_AMR_WB_8.85_ms]
		,[Playing_AMR_WB_12.65_ms]
		,[Playing_AMR_WB_14.25_ms]
		,[Playing_AMR_WB_15.85_ms]
		,[Playing_AMR_WB_18.25_ms]
		,[Playing_AMR_WB_19.85_ms]
		,[Playing_AMR_WB_23.05_ms]
		,[Playing_AMR_WB_23.85_ms]
		,[Playing_EVS_5.9_ms]
		,[Playing_EVS_7.2_ms]
		,[Playing_EVS_8_ms]
		,[Playing_EVS_9.6_ms]
		,[Playing_EVS_13.2_ms]
		,[Playing_EVS_16.4_ms]
		,[Playing_EVS_24.4_ms]
		,[Playing_EVS_32_ms]
		,[Playing_EVS_48_ms]
		,[Playing_EVS_64_ms]
		,[Playing_EVS_96_ms]
		,[Playing_EVS_128_ms]
		,Playing_MinRxLev
		,Playing_AvgRxLev
		,Playing_MaxRxLev
		,Playing_MinRxQual
		,Playing_AvgRxQual
		,Playing_MaxRxQual
		,Playing_MinRSCP
		,Playing_AvgRSCP
		,Playing_MaxRSCP
		,Playing_MinEcIo
		,Playing_AvgEcIo
		,Playing_MaxEcIo
		,Playing_MinTxPwr3G
		,Playing_AvgTxPwr3G
		,Playing_MaxTxPwr3G
		,Playing_MinRSRP
		,Playing_AvgRSRP
		,Playing_MaxRSRP
		,Playing_MinRSRQ
		,Playing_AvgRSRQ
		,Playing_MaxRSRQ
		,Playing_MinSINR
		,Playing_AvgSINR
		,Playing_MaxSINR
		,Playing_MinTxPwr4G
		,Playing_AvgTxPwr4G
		,Playing_MaxTxPwr4G
		,Playing_Handovers
		,Playing_Speed_kmh
		,Playing_Longitude
		,Playing_Latitude
		,[Recording Technology]
		,[Recording Technology Detailed]
		,[Recording Codec]
		,[Recording Codec Detailed]
		,Recording_AMR_NB_ms
		,Recording_AMR_WB_ms
		,Recording_EVS_ms
		,[Recording_AMR_NB_1.8_ms]
		,[Recording_AMR_NB_4.75_ms]
		,[Recording_AMR_NB_5.15_ms]
		,[Recording_AMR_NB_5.9_ms]
		,[Recording_AMR_NB_6.7_ms]
		,[Recording_AMR_NB_7.4_ms]
		,[Recording_AMR_NB_7.95_ms]
		,[Recording_AMR_NB_10.2_ms]
		,[Recording_AMR_NB_12.2_ms]
		,[Recording_AMR_WB_6.6_ms]
		,[Recording_AMR_WB_8.85_ms]
		,[Recording_AMR_WB_12.65_ms]
		,[Recording_AMR_WB_14.25_ms]
		,[Recording_AMR_WB_15.85_ms]
		,[Recording_AMR_WB_18.25_ms]
		,[Recording_AMR_WB_19.85_ms]
		,[Recording_AMR_WB_23.05_ms]
		,[Recording_AMR_WB_23.85_ms]
		,[Recording_EVS_5.9_ms]
		,[Recording_EVS_7.2_ms]
		,[Recording_EVS_8_ms]
		,[Recording_EVS_9.6_ms]
		,[Recording_EVS_13.2_ms]
		,[Recording_EVS_16.4_ms]
		,[Recording_EVS_24.4_ms]
		,[Recording_EVS_32_ms]
		,[Recording_EVS_48_ms]
		,[Recording_EVS_64_ms]
		,[Recording_EVS_96_ms]
		,[Recording_EVS_128_ms]
		,Recording_MinRxLev
		,Recording_AvgRxLev
		,Recording_MaxRxLev
		,Recording_MinRxQual
		,Recording_AvgRxQual
		,Recording_MaxRxQual
		,Recording_MinRSCP
		,Recording_AvgRSCP
		,Recording_MaxRSCP
		,Recording_MinEcIo
		,Recording_AvgEcIo
		,Recording_MaxEcIo
		,Recording_MinTxPwr3G
		,Recording_AvgTxPwr3G
		,Recording_MaxTxPwr3G
		,Recording_MinRSRP
		,Recording_AvgRSRP
		,Recording_MaxRSRP
		,Recording_MinRSRQ
		,Recording_AvgRSRQ
		,Recording_MaxRSRQ
		,Recording_MinSINR
		,Recording_AvgSINR
		,Recording_MaxSINR
		,Recording_MinTxPwr4G
		,Recording_AvgTxPwr4G
		,Recording_MaxTxPwr4G
		,Recording_Handovers
		,Recording_Speed_kmh
		,Recording_Longitude
		,Recording_Latitude
		,Region
		,Vendor
from NEW_CDR_SPEECH_2018 
WHERE Validity = 1 and [Operator] like (SELECT Operator FROM NEW_OPERATORS_PRIORITY_2018 WHERE SequenceNumber = 1)
--ORDER BY Call_Start_Time,TestStart

GO
CREATE VIEW [dbo].[vSpeechCDR2018_Operator2] 
AS
select   Campaign
		,File_Name_A
		,File_Name_B
		,FileID_A
		,FileId_B
		,SessionID_A
		,SessionId_B
		,Sequenz_ID_per_File_A
		,Call_Status
		,Call_Start_Time
		,Call_End_Time
		,System_A
		,System_Software_A
		,Channel_A
		,Channel_Description_A
		,System_B
		,System_Software_B
		,Channel_B
		,Channel_Description_B
		,Operator
		,Session_Type
		,Call_Direction
		,DialedNumber
		,L1_callMode_A
		,L2_callMode_A
		,L1_callMode_B
		,L2_callMode_B
		,Year
		,Week
		,Month
		,Day
		,Hour
		,G_Level_1
		,G_Level_2
		,G_Level_3
		,G_Level_4
		,G_Level_5
		,TrainType
		,Fleet
		,WagonNumber
		,WagonRepeter
		,UE_A
		,FW_A
		,IMEI_A
		,IMSI_A
		,MSISDN_A
		,UE_B
		,FW_B
		,IMEI_B
		,IMSI_B
		,MSISDN_B
		,TestId
		,direction
		,SpeedAvg
		,TestStart
		,TestEnd
		,LQ
		,L1_VoLTE_Call_Mode_LQ
		,L2_VoLTE_Call_Mode_LQ
		,qualityCode
		,LQCat
		,timeClipping
		,posFreqShift
		,negFreqShift
		,refDCOffset
		,codedDcOffset
		,delaySpread
		,codedLevel
		,delayDeviation
		,aSLrcvP56
		,activityRcvP56
		,noiseRcv
		,staticSNR
		,appl
		,ReceiveDelay
		,AmplClipping
		,MissedVoice
		,LowerFilterLimit
		,UpperFilterLimit
		,ErrCode
		,WideBand
		,BW
		,Resampling
		,Playing_Technology
		,Playing_Technology_Detailed
		,Playing_Codec
		,Playing_Codec_Detailed
		,Playing_AMR_NB_ms
		,Playing_AMR_WB_ms
		,Playing_EVS_ms
		,[Playing_AMR_NB_1.8_ms]
		,[Playing_AMR_NB_4.75_ms]
		,[Playing_AMR_NB_5.15_ms]
		,[Playing_AMR_NB_5.9_ms]
		,[Playing_AMR_NB_6.7_ms]
		,[Playing_AMR_NB_7.4_ms]
		,[Playing_AMR_NB_7.95_ms]
		,[Playing_AMR_NB_10.2_ms]
		,[Playing_AMR_NB_12.2_ms]
		,[Playing_AMR_WB_6.6_ms]
		,[Playing_AMR_WB_8.85_ms]
		,[Playing_AMR_WB_12.65_ms]
		,[Playing_AMR_WB_14.25_ms]
		,[Playing_AMR_WB_15.85_ms]
		,[Playing_AMR_WB_18.25_ms]
		,[Playing_AMR_WB_19.85_ms]
		,[Playing_AMR_WB_23.05_ms]
		,[Playing_AMR_WB_23.85_ms]
		,[Playing_EVS_5.9_ms]
		,[Playing_EVS_7.2_ms]
		,[Playing_EVS_8_ms]
		,[Playing_EVS_9.6_ms]
		,[Playing_EVS_13.2_ms]
		,[Playing_EVS_16.4_ms]
		,[Playing_EVS_24.4_ms]
		,[Playing_EVS_32_ms]
		,[Playing_EVS_48_ms]
		,[Playing_EVS_64_ms]
		,[Playing_EVS_96_ms]
		,[Playing_EVS_128_ms]
		,Playing_MinRxLev
		,Playing_AvgRxLev
		,Playing_MaxRxLev
		,Playing_MinRxQual
		,Playing_AvgRxQual
		,Playing_MaxRxQual
		,Playing_MinRSCP
		,Playing_AvgRSCP
		,Playing_MaxRSCP
		,Playing_MinEcIo
		,Playing_AvgEcIo
		,Playing_MaxEcIo
		,Playing_MinTxPwr3G
		,Playing_AvgTxPwr3G
		,Playing_MaxTxPwr3G
		,Playing_MinRSRP
		,Playing_AvgRSRP
		,Playing_MaxRSRP
		,Playing_MinRSRQ
		,Playing_AvgRSRQ
		,Playing_MaxRSRQ
		,Playing_MinSINR
		,Playing_AvgSINR
		,Playing_MaxSINR
		,Playing_MinTxPwr4G
		,Playing_AvgTxPwr4G
		,Playing_MaxTxPwr4G
		,Playing_Handovers
		,Playing_Speed_kmh
		,Playing_Longitude
		,Playing_Latitude
		,[Recording Technology]
		,[Recording Technology Detailed]
		,[Recording Codec]
		,[Recording Codec Detailed]
		,Recording_AMR_NB_ms
		,Recording_AMR_WB_ms
		,Recording_EVS_ms
		,[Recording_AMR_NB_1.8_ms]
		,[Recording_AMR_NB_4.75_ms]
		,[Recording_AMR_NB_5.15_ms]
		,[Recording_AMR_NB_5.9_ms]
		,[Recording_AMR_NB_6.7_ms]
		,[Recording_AMR_NB_7.4_ms]
		,[Recording_AMR_NB_7.95_ms]
		,[Recording_AMR_NB_10.2_ms]
		,[Recording_AMR_NB_12.2_ms]
		,[Recording_AMR_WB_6.6_ms]
		,[Recording_AMR_WB_8.85_ms]
		,[Recording_AMR_WB_12.65_ms]
		,[Recording_AMR_WB_14.25_ms]
		,[Recording_AMR_WB_15.85_ms]
		,[Recording_AMR_WB_18.25_ms]
		,[Recording_AMR_WB_19.85_ms]
		,[Recording_AMR_WB_23.05_ms]
		,[Recording_AMR_WB_23.85_ms]
		,[Recording_EVS_5.9_ms]
		,[Recording_EVS_7.2_ms]
		,[Recording_EVS_8_ms]
		,[Recording_EVS_9.6_ms]
		,[Recording_EVS_13.2_ms]
		,[Recording_EVS_16.4_ms]
		,[Recording_EVS_24.4_ms]
		,[Recording_EVS_32_ms]
		,[Recording_EVS_48_ms]
		,[Recording_EVS_64_ms]
		,[Recording_EVS_96_ms]
		,[Recording_EVS_128_ms]
		,Recording_MinRxLev
		,Recording_AvgRxLev
		,Recording_MaxRxLev
		,Recording_MinRxQual
		,Recording_AvgRxQual
		,Recording_MaxRxQual
		,Recording_MinRSCP
		,Recording_AvgRSCP
		,Recording_MaxRSCP
		,Recording_MinEcIo
		,Recording_AvgEcIo
		,Recording_MaxEcIo
		,Recording_MinTxPwr3G
		,Recording_AvgTxPwr3G
		,Recording_MaxTxPwr3G
		,Recording_MinRSRP
		,Recording_AvgRSRP
		,Recording_MaxRSRP
		,Recording_MinRSRQ
		,Recording_AvgRSRQ
		,Recording_MaxRSRQ
		,Recording_MinSINR
		,Recording_AvgSINR
		,Recording_MaxSINR
		,Recording_MinTxPwr4G
		,Recording_AvgTxPwr4G
		,Recording_MaxTxPwr4G
		,Recording_Handovers
		,Recording_Speed_kmh
		,Recording_Longitude
		,Recording_Latitude
		,Region
		,Vendor
from NEW_CDR_SPEECH_2018 
WHERE Validity = 1 and [Operator] like (SELECT Operator FROM NEW_OPERATORS_PRIORITY_2018 WHERE SequenceNumber = 2)
--ORDER BY Call_Start_Time,TestStart

GO
CREATE VIEW [dbo].[vSpeechCDR2018_Operator3] 
AS
select   Campaign
		,File_Name_A
		,File_Name_B
		,FileID_A
		,FileId_B
		,SessionID_A
		,SessionId_B
		,Sequenz_ID_per_File_A
		,Call_Status
		,Call_Start_Time
		,Call_End_Time
		,System_A
		,System_Software_A
		,Channel_A
		,Channel_Description_A
		,System_B
		,System_Software_B
		,Channel_B
		,Channel_Description_B
		,Operator
		,Session_Type
		,Call_Direction
		,DialedNumber
		,L1_callMode_A
		,L2_callMode_A
		,L1_callMode_B
		,L2_callMode_B
		,Year
		,Week
		,Month
		,Day
		,Hour
		,G_Level_1
		,G_Level_2
		,G_Level_3
		,G_Level_4
		,G_Level_5
		,TrainType
		,Fleet
		,WagonNumber
		,WagonRepeter
		,UE_A
		,FW_A
		,IMEI_A
		,IMSI_A
		,MSISDN_A
		,UE_B
		,FW_B
		,IMEI_B
		,IMSI_B
		,MSISDN_B
		,TestId
		,direction
		,SpeedAvg
		,TestStart
		,TestEnd
		,LQ
		,L1_VoLTE_Call_Mode_LQ
		,L2_VoLTE_Call_Mode_LQ
		,qualityCode
		,LQCat
		,timeClipping
		,posFreqShift
		,negFreqShift
		,refDCOffset
		,codedDcOffset
		,delaySpread
		,codedLevel
		,delayDeviation
		,aSLrcvP56
		,activityRcvP56
		,noiseRcv
		,staticSNR
		,appl
		,ReceiveDelay
		,AmplClipping
		,MissedVoice
		,LowerFilterLimit
		,UpperFilterLimit
		,ErrCode
		,WideBand
		,BW
		,Resampling
		,Playing_Technology
		,Playing_Technology_Detailed
		,Playing_Codec
		,Playing_Codec_Detailed
		,Playing_AMR_NB_ms
		,Playing_AMR_WB_ms
		,Playing_EVS_ms
		,[Playing_AMR_NB_1.8_ms]
		,[Playing_AMR_NB_4.75_ms]
		,[Playing_AMR_NB_5.15_ms]
		,[Playing_AMR_NB_5.9_ms]
		,[Playing_AMR_NB_6.7_ms]
		,[Playing_AMR_NB_7.4_ms]
		,[Playing_AMR_NB_7.95_ms]
		,[Playing_AMR_NB_10.2_ms]
		,[Playing_AMR_NB_12.2_ms]
		,[Playing_AMR_WB_6.6_ms]
		,[Playing_AMR_WB_8.85_ms]
		,[Playing_AMR_WB_12.65_ms]
		,[Playing_AMR_WB_14.25_ms]
		,[Playing_AMR_WB_15.85_ms]
		,[Playing_AMR_WB_18.25_ms]
		,[Playing_AMR_WB_19.85_ms]
		,[Playing_AMR_WB_23.05_ms]
		,[Playing_AMR_WB_23.85_ms]
		,[Playing_EVS_5.9_ms]
		,[Playing_EVS_7.2_ms]
		,[Playing_EVS_8_ms]
		,[Playing_EVS_9.6_ms]
		,[Playing_EVS_13.2_ms]
		,[Playing_EVS_16.4_ms]
		,[Playing_EVS_24.4_ms]
		,[Playing_EVS_32_ms]
		,[Playing_EVS_48_ms]
		,[Playing_EVS_64_ms]
		,[Playing_EVS_96_ms]
		,[Playing_EVS_128_ms]
		,Playing_MinRxLev
		,Playing_AvgRxLev
		,Playing_MaxRxLev
		,Playing_MinRxQual
		,Playing_AvgRxQual
		,Playing_MaxRxQual
		,Playing_MinRSCP
		,Playing_AvgRSCP
		,Playing_MaxRSCP
		,Playing_MinEcIo
		,Playing_AvgEcIo
		,Playing_MaxEcIo
		,Playing_MinTxPwr3G
		,Playing_AvgTxPwr3G
		,Playing_MaxTxPwr3G
		,Playing_MinRSRP
		,Playing_AvgRSRP
		,Playing_MaxRSRP
		,Playing_MinRSRQ
		,Playing_AvgRSRQ
		,Playing_MaxRSRQ
		,Playing_MinSINR
		,Playing_AvgSINR
		,Playing_MaxSINR
		,Playing_MinTxPwr4G
		,Playing_AvgTxPwr4G
		,Playing_MaxTxPwr4G
		,Playing_Handovers
		,Playing_Speed_kmh
		,Playing_Longitude
		,Playing_Latitude
		,[Recording Technology]
		,[Recording Technology Detailed]
		,[Recording Codec]
		,[Recording Codec Detailed]
		,Recording_AMR_NB_ms
		,Recording_AMR_WB_ms
		,Recording_EVS_ms
		,[Recording_AMR_NB_1.8_ms]
		,[Recording_AMR_NB_4.75_ms]
		,[Recording_AMR_NB_5.15_ms]
		,[Recording_AMR_NB_5.9_ms]
		,[Recording_AMR_NB_6.7_ms]
		,[Recording_AMR_NB_7.4_ms]
		,[Recording_AMR_NB_7.95_ms]
		,[Recording_AMR_NB_10.2_ms]
		,[Recording_AMR_NB_12.2_ms]
		,[Recording_AMR_WB_6.6_ms]
		,[Recording_AMR_WB_8.85_ms]
		,[Recording_AMR_WB_12.65_ms]
		,[Recording_AMR_WB_14.25_ms]
		,[Recording_AMR_WB_15.85_ms]
		,[Recording_AMR_WB_18.25_ms]
		,[Recording_AMR_WB_19.85_ms]
		,[Recording_AMR_WB_23.05_ms]
		,[Recording_AMR_WB_23.85_ms]
		,[Recording_EVS_5.9_ms]
		,[Recording_EVS_7.2_ms]
		,[Recording_EVS_8_ms]
		,[Recording_EVS_9.6_ms]
		,[Recording_EVS_13.2_ms]
		,[Recording_EVS_16.4_ms]
		,[Recording_EVS_24.4_ms]
		,[Recording_EVS_32_ms]
		,[Recording_EVS_48_ms]
		,[Recording_EVS_64_ms]
		,[Recording_EVS_96_ms]
		,[Recording_EVS_128_ms]
		,Recording_MinRxLev
		,Recording_AvgRxLev
		,Recording_MaxRxLev
		,Recording_MinRxQual
		,Recording_AvgRxQual
		,Recording_MaxRxQual
		,Recording_MinRSCP
		,Recording_AvgRSCP
		,Recording_MaxRSCP
		,Recording_MinEcIo
		,Recording_AvgEcIo
		,Recording_MaxEcIo
		,Recording_MinTxPwr3G
		,Recording_AvgTxPwr3G
		,Recording_MaxTxPwr3G
		,Recording_MinRSRP
		,Recording_AvgRSRP
		,Recording_MaxRSRP
		,Recording_MinRSRQ
		,Recording_AvgRSRQ
		,Recording_MaxRSRQ
		,Recording_MinSINR
		,Recording_AvgSINR
		,Recording_MaxSINR
		,Recording_MinTxPwr4G
		,Recording_AvgTxPwr4G
		,Recording_MaxTxPwr4G
		,Recording_Handovers
		,Recording_Speed_kmh
		,Recording_Longitude
		,Recording_Latitude
		,Region
		,Vendor
from NEW_CDR_SPEECH_2018 
WHERE Validity = 1 and [Operator] like (SELECT Operator FROM NEW_OPERATORS_PRIORITY_2018 WHERE SequenceNumber = 3)
--ORDER BY Call_Start_Time,TestStart

GO
CREATE VIEW [dbo].[vSpeechCDR2018_Operator4] 
AS
select   Campaign
		,File_Name_A
		,File_Name_B
		,FileID_A
		,FileId_B
		,SessionID_A
		,SessionId_B
		,Sequenz_ID_per_File_A
		,Call_Status
		,Call_Start_Time
		,Call_End_Time
		,System_A
		,System_Software_A
		,Channel_A
		,Channel_Description_A
		,System_B
		,System_Software_B
		,Channel_B
		,Channel_Description_B
		,Operator
		,Session_Type
		,Call_Direction
		,DialedNumber
		,L1_callMode_A
		,L2_callMode_A
		,L1_callMode_B
		,L2_callMode_B
		,Year
		,Week
		,Month
		,Day
		,Hour
		,G_Level_1
		,G_Level_2
		,G_Level_3
		,G_Level_4
		,G_Level_5
		,TrainType
		,Fleet
		,WagonNumber
		,WagonRepeter
		,UE_A
		,FW_A
		,IMEI_A
		,IMSI_A
		,MSISDN_A
		,UE_B
		,FW_B
		,IMEI_B
		,IMSI_B
		,MSISDN_B
		,TestId
		,direction
		,SpeedAvg
		,TestStart
		,TestEnd
		,LQ
		,L1_VoLTE_Call_Mode_LQ
		,L2_VoLTE_Call_Mode_LQ
		,qualityCode
		,LQCat
		,timeClipping
		,posFreqShift
		,negFreqShift
		,refDCOffset
		,codedDcOffset
		,delaySpread
		,codedLevel
		,delayDeviation
		,aSLrcvP56
		,activityRcvP56
		,noiseRcv
		,staticSNR
		,appl
		,ReceiveDelay
		,AmplClipping
		,MissedVoice
		,LowerFilterLimit
		,UpperFilterLimit
		,ErrCode
		,WideBand
		,BW
		,Resampling
		,Playing_Technology
		,Playing_Technology_Detailed
		,Playing_Codec
		,Playing_Codec_Detailed
		,Playing_AMR_NB_ms
		,Playing_AMR_WB_ms
		,Playing_EVS_ms
		,[Playing_AMR_NB_1.8_ms]
		,[Playing_AMR_NB_4.75_ms]
		,[Playing_AMR_NB_5.15_ms]
		,[Playing_AMR_NB_5.9_ms]
		,[Playing_AMR_NB_6.7_ms]
		,[Playing_AMR_NB_7.4_ms]
		,[Playing_AMR_NB_7.95_ms]
		,[Playing_AMR_NB_10.2_ms]
		,[Playing_AMR_NB_12.2_ms]
		,[Playing_AMR_WB_6.6_ms]
		,[Playing_AMR_WB_8.85_ms]
		,[Playing_AMR_WB_12.65_ms]
		,[Playing_AMR_WB_14.25_ms]
		,[Playing_AMR_WB_15.85_ms]
		,[Playing_AMR_WB_18.25_ms]
		,[Playing_AMR_WB_19.85_ms]
		,[Playing_AMR_WB_23.05_ms]
		,[Playing_AMR_WB_23.85_ms]
		,[Playing_EVS_5.9_ms]
		,[Playing_EVS_7.2_ms]
		,[Playing_EVS_8_ms]
		,[Playing_EVS_9.6_ms]
		,[Playing_EVS_13.2_ms]
		,[Playing_EVS_16.4_ms]
		,[Playing_EVS_24.4_ms]
		,[Playing_EVS_32_ms]
		,[Playing_EVS_48_ms]
		,[Playing_EVS_64_ms]
		,[Playing_EVS_96_ms]
		,[Playing_EVS_128_ms]
		,Playing_MinRxLev
		,Playing_AvgRxLev
		,Playing_MaxRxLev
		,Playing_MinRxQual
		,Playing_AvgRxQual
		,Playing_MaxRxQual
		,Playing_MinRSCP
		,Playing_AvgRSCP
		,Playing_MaxRSCP
		,Playing_MinEcIo
		,Playing_AvgEcIo
		,Playing_MaxEcIo
		,Playing_MinTxPwr3G
		,Playing_AvgTxPwr3G
		,Playing_MaxTxPwr3G
		,Playing_MinRSRP
		,Playing_AvgRSRP
		,Playing_MaxRSRP
		,Playing_MinRSRQ
		,Playing_AvgRSRQ
		,Playing_MaxRSRQ
		,Playing_MinSINR
		,Playing_AvgSINR
		,Playing_MaxSINR
		,Playing_MinTxPwr4G
		,Playing_AvgTxPwr4G
		,Playing_MaxTxPwr4G
		,Playing_Handovers
		,Playing_Speed_kmh
		,Playing_Longitude
		,Playing_Latitude
		,[Recording Technology]
		,[Recording Technology Detailed]
		,[Recording Codec]
		,[Recording Codec Detailed]
		,Recording_AMR_NB_ms
		,Recording_AMR_WB_ms
		,Recording_EVS_ms
		,[Recording_AMR_NB_1.8_ms]
		,[Recording_AMR_NB_4.75_ms]
		,[Recording_AMR_NB_5.15_ms]
		,[Recording_AMR_NB_5.9_ms]
		,[Recording_AMR_NB_6.7_ms]
		,[Recording_AMR_NB_7.4_ms]
		,[Recording_AMR_NB_7.95_ms]
		,[Recording_AMR_NB_10.2_ms]
		,[Recording_AMR_NB_12.2_ms]
		,[Recording_AMR_WB_6.6_ms]
		,[Recording_AMR_WB_8.85_ms]
		,[Recording_AMR_WB_12.65_ms]
		,[Recording_AMR_WB_14.25_ms]
		,[Recording_AMR_WB_15.85_ms]
		,[Recording_AMR_WB_18.25_ms]
		,[Recording_AMR_WB_19.85_ms]
		,[Recording_AMR_WB_23.05_ms]
		,[Recording_AMR_WB_23.85_ms]
		,[Recording_EVS_5.9_ms]
		,[Recording_EVS_7.2_ms]
		,[Recording_EVS_8_ms]
		,[Recording_EVS_9.6_ms]
		,[Recording_EVS_13.2_ms]
		,[Recording_EVS_16.4_ms]
		,[Recording_EVS_24.4_ms]
		,[Recording_EVS_32_ms]
		,[Recording_EVS_48_ms]
		,[Recording_EVS_64_ms]
		,[Recording_EVS_96_ms]
		,[Recording_EVS_128_ms]
		,Recording_MinRxLev
		,Recording_AvgRxLev
		,Recording_MaxRxLev
		,Recording_MinRxQual
		,Recording_AvgRxQual
		,Recording_MaxRxQual
		,Recording_MinRSCP
		,Recording_AvgRSCP
		,Recording_MaxRSCP
		,Recording_MinEcIo
		,Recording_AvgEcIo
		,Recording_MaxEcIo
		,Recording_MinTxPwr3G
		,Recording_AvgTxPwr3G
		,Recording_MaxTxPwr3G
		,Recording_MinRSRP
		,Recording_AvgRSRP
		,Recording_MaxRSRP
		,Recording_MinRSRQ
		,Recording_AvgRSRQ
		,Recording_MaxRSRQ
		,Recording_MinSINR
		,Recording_AvgSINR
		,Recording_MaxSINR
		,Recording_MinTxPwr4G
		,Recording_AvgTxPwr4G
		,Recording_MaxTxPwr4G
		,Recording_Handovers
		,Recording_Speed_kmh
		,Recording_Longitude
		,Recording_Latitude
		,Region
		,Vendor
from NEW_CDR_SPEECH_2018 
WHERE Validity = 1 and [Operator] like (SELECT Operator FROM NEW_OPERATORS_PRIORITY_2018 WHERE SequenceNumber = 4)
--ORDER BY Call_Start_Time,TestStart

GO
CREATE VIEW [dbo].[vSpeechCDR2018_Operator5] 
AS
select   Campaign
		,File_Name_A
		,File_Name_B
		,FileID_A
		,FileId_B
		,SessionID_A
		,SessionId_B
		,Sequenz_ID_per_File_A
		,Call_Status
		,Call_Start_Time
		,Call_End_Time
		,System_A
		,System_Software_A
		,Channel_A
		,Channel_Description_A
		,System_B
		,System_Software_B
		,Channel_B
		,Channel_Description_B
		,Operator
		,Session_Type
		,Call_Direction
		,DialedNumber
		,L1_callMode_A
		,L2_callMode_A
		,L1_callMode_B
		,L2_callMode_B
		,Year
		,Week
		,Month
		,Day
		,Hour
		,G_Level_1
		,G_Level_2
		,G_Level_3
		,G_Level_4
		,G_Level_5
		,TrainType
		,Fleet
		,WagonNumber
		,WagonRepeter
		,UE_A
		,FW_A
		,IMEI_A
		,IMSI_A
		,MSISDN_A
		,UE_B
		,FW_B
		,IMEI_B
		,IMSI_B
		,MSISDN_B
		,TestId
		,direction
		,SpeedAvg
		,TestStart
		,TestEnd
		,LQ
		,L1_VoLTE_Call_Mode_LQ
		,L2_VoLTE_Call_Mode_LQ
		,qualityCode
		,LQCat
		,timeClipping
		,posFreqShift
		,negFreqShift
		,refDCOffset
		,codedDcOffset
		,delaySpread
		,codedLevel
		,delayDeviation
		,aSLrcvP56
		,activityRcvP56
		,noiseRcv
		,staticSNR
		,appl
		,ReceiveDelay
		,AmplClipping
		,MissedVoice
		,LowerFilterLimit
		,UpperFilterLimit
		,ErrCode
		,WideBand
		,BW
		,Resampling
		,Playing_Technology
		,Playing_Technology_Detailed
		,Playing_Codec
		,Playing_Codec_Detailed
		,Playing_AMR_NB_ms
		,Playing_AMR_WB_ms
		,Playing_EVS_ms
		,[Playing_AMR_NB_1.8_ms]
		,[Playing_AMR_NB_4.75_ms]
		,[Playing_AMR_NB_5.15_ms]
		,[Playing_AMR_NB_5.9_ms]
		,[Playing_AMR_NB_6.7_ms]
		,[Playing_AMR_NB_7.4_ms]
		,[Playing_AMR_NB_7.95_ms]
		,[Playing_AMR_NB_10.2_ms]
		,[Playing_AMR_NB_12.2_ms]
		,[Playing_AMR_WB_6.6_ms]
		,[Playing_AMR_WB_8.85_ms]
		,[Playing_AMR_WB_12.65_ms]
		,[Playing_AMR_WB_14.25_ms]
		,[Playing_AMR_WB_15.85_ms]
		,[Playing_AMR_WB_18.25_ms]
		,[Playing_AMR_WB_19.85_ms]
		,[Playing_AMR_WB_23.05_ms]
		,[Playing_AMR_WB_23.85_ms]
		,[Playing_EVS_5.9_ms]
		,[Playing_EVS_7.2_ms]
		,[Playing_EVS_8_ms]
		,[Playing_EVS_9.6_ms]
		,[Playing_EVS_13.2_ms]
		,[Playing_EVS_16.4_ms]
		,[Playing_EVS_24.4_ms]
		,[Playing_EVS_32_ms]
		,[Playing_EVS_48_ms]
		,[Playing_EVS_64_ms]
		,[Playing_EVS_96_ms]
		,[Playing_EVS_128_ms]
		,Playing_MinRxLev
		,Playing_AvgRxLev
		,Playing_MaxRxLev
		,Playing_MinRxQual
		,Playing_AvgRxQual
		,Playing_MaxRxQual
		,Playing_MinRSCP
		,Playing_AvgRSCP
		,Playing_MaxRSCP
		,Playing_MinEcIo
		,Playing_AvgEcIo
		,Playing_MaxEcIo
		,Playing_MinTxPwr3G
		,Playing_AvgTxPwr3G
		,Playing_MaxTxPwr3G
		,Playing_MinRSRP
		,Playing_AvgRSRP
		,Playing_MaxRSRP
		,Playing_MinRSRQ
		,Playing_AvgRSRQ
		,Playing_MaxRSRQ
		,Playing_MinSINR
		,Playing_AvgSINR
		,Playing_MaxSINR
		,Playing_MinTxPwr4G
		,Playing_AvgTxPwr4G
		,Playing_MaxTxPwr4G
		,Playing_Handovers
		,Playing_Speed_kmh
		,Playing_Longitude
		,Playing_Latitude
		,[Recording Technology]
		,[Recording Technology Detailed]
		,[Recording Codec]
		,[Recording Codec Detailed]
		,Recording_AMR_NB_ms
		,Recording_AMR_WB_ms
		,Recording_EVS_ms
		,[Recording_AMR_NB_1.8_ms]
		,[Recording_AMR_NB_4.75_ms]
		,[Recording_AMR_NB_5.15_ms]
		,[Recording_AMR_NB_5.9_ms]
		,[Recording_AMR_NB_6.7_ms]
		,[Recording_AMR_NB_7.4_ms]
		,[Recording_AMR_NB_7.95_ms]
		,[Recording_AMR_NB_10.2_ms]
		,[Recording_AMR_NB_12.2_ms]
		,[Recording_AMR_WB_6.6_ms]
		,[Recording_AMR_WB_8.85_ms]
		,[Recording_AMR_WB_12.65_ms]
		,[Recording_AMR_WB_14.25_ms]
		,[Recording_AMR_WB_15.85_ms]
		,[Recording_AMR_WB_18.25_ms]
		,[Recording_AMR_WB_19.85_ms]
		,[Recording_AMR_WB_23.05_ms]
		,[Recording_AMR_WB_23.85_ms]
		,[Recording_EVS_5.9_ms]
		,[Recording_EVS_7.2_ms]
		,[Recording_EVS_8_ms]
		,[Recording_EVS_9.6_ms]
		,[Recording_EVS_13.2_ms]
		,[Recording_EVS_16.4_ms]
		,[Recording_EVS_24.4_ms]
		,[Recording_EVS_32_ms]
		,[Recording_EVS_48_ms]
		,[Recording_EVS_64_ms]
		,[Recording_EVS_96_ms]
		,[Recording_EVS_128_ms]
		,Recording_MinRxLev
		,Recording_AvgRxLev
		,Recording_MaxRxLev
		,Recording_MinRxQual
		,Recording_AvgRxQual
		,Recording_MaxRxQual
		,Recording_MinRSCP
		,Recording_AvgRSCP
		,Recording_MaxRSCP
		,Recording_MinEcIo
		,Recording_AvgEcIo
		,Recording_MaxEcIo
		,Recording_MinTxPwr3G
		,Recording_AvgTxPwr3G
		,Recording_MaxTxPwr3G
		,Recording_MinRSRP
		,Recording_AvgRSRP
		,Recording_MaxRSRP
		,Recording_MinRSRQ
		,Recording_AvgRSRQ
		,Recording_MaxRSRQ
		,Recording_MinSINR
		,Recording_AvgSINR
		,Recording_MaxSINR
		,Recording_MinTxPwr4G
		,Recording_AvgTxPwr4G
		,Recording_MaxTxPwr4G
		,Recording_Handovers
		,Recording_Speed_kmh
		,Recording_Longitude
		,Recording_Latitude
		,Region
		,Vendor
from NEW_CDR_SPEECH_2018 
WHERE Validity = 1 and [Operator] like (SELECT Operator FROM NEW_OPERATORS_PRIORITY_2018 WHERE SequenceNumber = 5)
--ORDER BY Call_Start_Time,TestStart